language: ruby
rvm: 2.3.1

dist: trusty

matrix:
  include:
    - sudo: required
      group: travis_lts
      env: SUDO=required GROUP=travis_lts

install: true
script:
  - yarn global install bower
  - bower --version
