language: node_js
node_js: 8.9.3
env:
  global:
    - PATH="$HOME/.yarn/bin:$PATH"
install: true
script:
  - ls -al `which yarn`
  - yarn --version
  - echo $PATH
  - (yarn 2>/dev/null && test "$(yarn --version)" == "0.24.6") || curl -o- -L https://raw.githubusercontent.com/yarnpkg/website/6aa5c6721d6057c2072b117eae78dd9582d41575/install.sh | bash -s -- --version 0.24.6
  - echo $PATH
  - ls -al `which yarn`
  - cat `which yarn`
  - chmod +x fake-yarn.sh && cp fake-yarn.sh /home/travis/.yarn/bin/ && fake-yarn.sh --version
  - cat /home/travis/.yarn/bin/yarn.js
  - node /home/travis/.yarn/bin/yarn.js --version
  - winpty node /home/travis/.yarn/bin/yarn.js --version
  - yarn --version
