language: objective-c

osx_image:
  - xcode10.1
  - xcode9.3

matrix:
  include:
    - language: ruby
      dist: trusty
      env: DIST=trusty
    - language: ruby
      dist: xenial
      env: DIST=xenial

install: true
script: true

notifications:
  email: false
