language: python

dist: trusty

python:
  - 2.6.9
  - 2.7.10
  - 3.2.6
  - 3.5.0

install: true
script:
  - export CURRENT_PYTHON_VERSION=`python --version`
  - if [ $CURRENT_PYTHON_VERSION != "Python $TRAVIS_PYTHON_VERSION" ]; then false; fi
